ES = {
"%1$s in %2$d days": "%1$s en %2$d días",
"%1$s new, %2$s already there, %3$s skipped, %4$s invalid": "%1$s nuevos, %2$s ya estaban, %3$s omitidos, %4$s no válidos",
"%1$s new, %2$s unsubscribed": "Altas: %1$s · bajas: %2$s",
"%1$s of %2$s": "%1$s de %2$s",
"%1$s people take about %2$s hours": "%1$s personas tardan unas %2$s horas",
"%1$s people take about %2$s minutes": "%1$s personas tardan unos %2$s minutos",
"%1$s–%2$s of %3$s": "%1$s–%2$s de %3$s",
"%d characters": "%d caracteres",
"%d days": "%d días",
"%d of 5": "%d de 5",
"%s ago": "hace %s",
"%s has been removed from the list. If it was a mistake, you can subscribe again from the website.": "%s ya no está en la lista. Si fue un error, puedes volver a suscribirte desde la web.",
"%s hours": "%s horas",
"%s left. Nothing goes out until you resume it.": "Quedan %s. No sale nada hasta que lo reanudes.",
"%s minutes": "%s minutos",
"%s of the opens came in the first 3 hours.": "El %s de las aperturas llegó en las 3 primeras horas.",
"%s per hour": "%s por hora",
"%s person": "%s persona",
"%s points above your average": "%s puntos por encima de tu media",
"%s points below your average": "%s puntos por debajo de tu media",
"%s will not receive more emails from us.": "%s no recibirá más correos nuestros.",
"%s will stop receiving our newsletter.": "%s dejará de recibir nuestro boletín.",
"(empty)": "(vacío)",
"(no subject)": "(sin asunto)",
"+%s": "+%s",
"30 days": "30 días",
"<b>All images</b> have alternative text": "<b>Todas las imágenes</b> tienen texto alternativo",
"<b>No postal address.</b> Add it in Settings: CAN-SPAM requires it.": "<b>Falta la dirección postal.</b> Ponla en Ajustes: la ley CAN-SPAM la exige.",
"<b>No test sent yet.</b> Send yourself one before scheduling it.": "<b>Sin prueba enviada todavía.</b> Mándate una antes de programarla.",
"<b>Postal address</b> in the footer, as required by CAN-SPAM": "<b>Dirección postal</b> en el pie, como pide la ley CAN-SPAM",
"<b>Some image has no alternative text.</b> It is what is read when images are blocked.": "<b>Alguna imagen no tiene texto alternativo.</b> Es lo que se lee cuando las imágenes están bloqueadas.",
"<b>Test sent.</b> Check it on your phone too.": "<b>Prueba enviada.</b> Mírala también en el móvil.",
"<b>Unsubscribe link</b> and the one-click unsubscribe header that Gmail and Yahoo require": "<b>Enlace de baja</b> y la cabecera de baja con un clic que piden Gmail y Yahoo",
"A CSV from Mailchimp, Excel or wherever you have it.": "Un CSV de Mailchimp, de Excel o de donde la tengas.",
"A CSV with a column for the email. If it has columns for the name (first name, last name or name), they are used too. Exports from Mailchimp, Excel or Google Sheets work as they are.": "Un CSV con una columna para el correo. Si trae columnas de nombre (nombre, apellido o nombre completo), también se usan. Lo que exportan Mailchimp, Excel o Google Sheets sirve tal cual.",
"A form on the website": "Un formulario en la web",
"A line that invites to open it": "Una línea que invite a abrirlo",
"A person's name is opened more than a company's: «Ana from Acme» better than «Acme Newsletter».": "Un nombre de persona se abre más que uno de empresa: mejor «Ana de Acme» que «Boletín Acme».",
"Actions": "Acciones",
"Active": "Activos",
"Active subscribers": "Suscriptores activos",
"Add": "Añadir",
"Add subscriber": "Añadir suscriptor",
"Added by hand": "Añadidos a mano",
"Address": "Dirección",
"After sending": "Al enviar",
"After some seconds": "A los pocos segundos",
"Align": "Alinear",
"All": "Todas",
"All lists": "Todas las listas",
"All subscribers": "Todos los suscriptores",
"Almost done! Check your inbox and confirm with one click.": "¡Casi listo! Revisa tu correo y confirma con un clic.",
"Alt text": "Texto alternativo",
"Amazon SES did not accept the connection: %s": "Amazon SES no aceptó la conexión: %s",
"Amazon SES is missing the SMTP user or password.": "A Amazon SES le falta el usuario o la contraseña SMTP.",
"Apply": "Aplicar",
"Ask for the name": "Pedir el nombre",
"At the top if there is no logo, and in the footer.": "Arriba si no hay logo, y en el pie.",
"Average open rate": "Apertura media",
"Back to campaigns": "Volver a campañas",
"Back to draft": "Volver a borrador",
"Before sending": "Antes de enviar",
"Below 0.5 % is considered healthy": "Por debajo del 0,5 % se considera sano",
"Below it always go the unsubscribe link and the postal address.": "Debajo siempre van el enlace de baja y la dirección postal.",
"Better an address @%s: Gmail checks that the sender matches the domain.": "Mejor una dirección @%s: Gmail comprueba que el remitente coincida con el dominio.",
"Between 30 and 50 characters is read in full on a phone": "Entre 30 y 50 caracteres se lee entero en el móvil",
"Black": "Negro",
"Blocks": "Bloques",
"Blog post": "Entrada del blog",
"Bold": "Negrita",
"Bottom bar": "Barra inferior",
"Bounced": "Rebotados",
"Brand color": "Color de marca",
"Brand in the email": "La marca en el correo",
"Bring your list": "Trae tu lista",
"Bring your list in a CSV or put a form on the website. They will appear here.": "Trae tu lista en un CSV o pon un formulario en la web. Aparecerán aquí.",
"Button": "Botón",
"Came from": "Llegó por",
"Campaign": "Campaña",
"Campaign not found": "No se encontró la campaña",
"Campaigns": "Campañas",
"Cancel": "Cancelar",
"Cancel sending": "Cancelar el envío",
"Cancelled": "Cancelada",
"Center": "Centro",
"Change": "Cambiar",
"Change date": "Cambiar fecha",
"Change it in Settings": "Cámbialo en Ajustes",
"Check the forms": "Revisa los formularios",
"Checking with Amazon…": "Comprobando con Amazon…",
"Choose": "Elegir",
"Choose a CSV file.": "Elige un archivo CSV.",
"Choose a date": "Elegir fecha",
"Choose an image": "Elige una imagen",
"Street, city, state, ZIP": "Calle, ciudad, estado, código postal",
"Clear the search": "Quitar la búsqueda",
"Clicks": "Clics",
"Close": "Cerrar",
"Color": "Color",
"Company": "Empresa",
"Configured": "Configurado",
"Confirm": "Confirmar",
"Confirm that these people agreed to receive your emails.": "Confirma que estas personas aceptaron recibir tus correos.",
"Confirm that this person agreed to receive your emails.": "Confirma que esta persona aceptó recibir tus correos.",
"Confirm that you want to receive our newsletter. If it was not you, ignore this email and nothing will happen.": "Confirma que quieres recibir nuestro boletín. Si no fuiste tú, ignora este correo y no pasará nada.",
"Confirm your subscription": "Confirma tu suscripción",
"Confirmation": "Confirmación",
"Confirmation sent": "Confirmación enviada",
"Copied": "Copiado",
"Copy": "Copiar",
"Could not connect to Amazon SES.": "No se pudo conectar con Amazon SES.",
"Count clicks": "Contar los clics",
"Count opens": "Contar las aperturas",
"Counted again when it goes out: whoever opens the original in the meantime will not receive it.": "Se vuelve a contar al enviarla: quien abra la original mientras tanto ya no la recibe.",
"Dark": "Oscuro",
"Dark with the brand glow, or light with a fine border.": "Oscuro con el brillo de la marca, o claro con un borde fino.",
"Delete": "Borrar",
"Delete list": "Borrar la lista",
"Delete this list? The people stay in the other lists.": "¿Borrar esta lista? Las personas siguen en las demás listas.",
"Delete this subscriber completely? Their sends stay in the reports, without their email.": "¿Borrar del todo a este suscriptor? Sus envíos se quedan en los informes, sin su correo.",
"Deleting a list does not delete the people: they stay in the other lists.": "Borrar una lista no borra a la gente: siguen en las demás listas.",
"Desktop": "Ordenador",
"Discard": "Descartar",
"Divider": "Separador",
"Do you want to unsubscribe?": "¿Quieres darte de baja?",
"Done": "Hecho",
"Done! You are subscribed.": "¡Listo! Ya estás suscrito.",
"Done, you will not receive more emails": "Listo, no recibirás más correos",
"Double confirmation": "Doble confirmación",
"Draft": "Borrador",
"Drafts": "Borradores",
"Drag to reorder": "Arrastra para ordenar",
"Duplicate": "Duplicar",
"Edit": "Editar",
"Edited %s": "Editada %s",
"Email": "Correo",
"Email field": "Campo de correo",
"Email preview": "Vista previa del correo",
"Emails per hour": "Correos por hora",
"Everything saved": "Todo guardado",
"Export CSV": "Exportar CSV",
"Failed sends": "Envíos fallidos",
"Fields: {first_name}, {last_name}, {email}. With a fallback: {first_name|friend}.": "Campos: {first_name}, {last_name}, {email}. Con respaldo: {first_name|amigo}.",
"File": "Archivo",
"First 24 hours": "Primeras 24 horas",
"First campaign": "Primera campaña",
"First name": "Nombre",
"First steps": "Primeros pasos",
"First subscribers": "Primeros suscriptores",
"Fixed, can be closed": "Fija, se puede cerrar",
"Footer of the emails": "Pie de los correos",
"For big lists. About 0.10 USD per 1,000 emails, and it does not use up the server quota.": "Para listas grandes. Unos 0,10 USD por cada 1.000 correos, y no gasta el cupo del servidor.",
"For the «brand color» buttons and the glow of the forms.": "Para los botones «color de marca» y el brillo de los formularios.",
"Form": "Formulario",
"Forms": "Formularios",
"From": "Remitente",
"General": "General",
"Give the list a name.": "Ponle un nombre a la lista.",
"Gmail and the iPhone Mail app load the images by themselves when the email arrives, so some opens are not a person reading. Clicks are the reliable figure.": "Gmail y Mail del iPhone cargan las imágenes solos al llegar el correo, así que algunas aperturas no son una persona leyendo. Los clics son la cifra fiable.",
"Gmail asks to keep spam complaints below 0.3 %.": "Gmail pide que las quejas de spam no pasen del 0,3 %.",
"Go to the website": "Ir a la web",
"Goes out by itself when someone confirms their subscription.": "Sale sola cuando alguien confirma su suscripción.",
"Goes out through the server": "Sale por el servidor",
"Going out at %s per hour to leave room for the website emails": "Sale a %s por hora para dejar sitio a los correos de la web",
"Good": "Buena",
"Height": "Alto",
"Hi {first_name|there},": "Hola, {first_name|amigo}:",
"How the emails go out": "Cómo salen los correos",
"Image": "Imagen",
"Import": "Importar",
"Import CSV": "Importar CSV",
"Import subscribers": "Importar suscriptores",
"Imported": "Importados",
"In a page": "En la página",
"In a page, as a pop-up or as a bottom bar.": "En una página, como ventana emergente o como barra inferior.",
"In the SES console, «SMTP settings». It depends on the region: email-smtp.us-east-2.amazonaws.com is Ohio.": "En la consola de SES, «SMTP settings». Depende de la región: email-smtp.us-east-2.amazonaws.com es Ohio.",
"Interest": "Interés",
"Interest comes from their last 5 emails: an open adds a point, a click adds two.": "El interés sale de sus últimos 5 correos: abrir suma un punto y hacer clic suma dos.",
"It is saved encrypted and never shown again. When saving, the connection with Amazon is checked.": "Se guarda cifrada y no se vuelve a enseñar. Al guardar se comprueba la conexión con Amazon.",
"It may have been used already. If you want to subscribe, use the form on the website again.": "Puede que ya se haya usado. Si quieres suscribirte, usa otra vez el formulario de la web.",
"It will go to %1$s. At %2$s per hour, it takes about %3$s.": "Le llegará a %1$s. A %2$s por hora, tarda unas %3$s.",
"Italic": "Cursiva",
"Join %s subscribers": "Ya somos %s",
"Joined": "Alta",
"Joined %1$s · %2$s": "Alta %1$s · %2$s",
"Keep an eye on it": "Vigílala",
"Large": "Grande",
"Last 90 days. Above 2 % hurts delivery.": "Últimos 90 días. Por encima del 2 % perjudica la entrega.",
"Last name": "Apellido",
"Latest campaigns": "Últimas campañas",
"Left": "Izquierda",
"Light": "Claro",
"Link": "Enlace",
"Link address (https://…)": "Dirección del enlace (https://…)",
"Link text": "Texto del enlace",
"List": "Lista",
"List health": "Salud de la lista",
"List name": "Nombre de la lista",
"Lists": "Listas",
"Live preview, with your name in the fields": "Vista previa en vivo, con tu nombre en los campos",
"Logo": "Logo",
"Logo for the emails": "Logo para los correos",
"Look and behavior": "Aspecto y comportamiento",
"Main form": "Formulario principal",
"Mark as active": "Marcar como activo",
"Medium": "Mediano",
"Move down": "Bajar",
"Move up": "Subir",
"Name": "Nombre",
"Needs attention": "Necesita atención",
"New": "Nuevo",
"New campaign": "Nueva campaña",
"New form": "Nuevo formulario",
"New list": "Nueva lista",
"Newsletter %s": "Boletín %s",
"Newsletters and email campaigns from your own WordPress.": "Boletines y campañas de correo desde tu propio WordPress.",
"Next send": "Próximo envío",
"No campaign has been sent yet.": "Todavía no se ha enviado ninguna campaña.",
"No campaign matches.": "Ninguna campaña coincide.",
"No campaigns yet": "Aún no hay campañas",
"No clicks yet.": "Aún no hay clics.",
"No email column was found in the file.": "No se encontró ninguna columna de correo en el archivo.",
"No failures": "Sin fallos",
"No opens in 6 months": "Sin abrir en 6 meses",
"No opens yet. They usually start arriving a few minutes after sending.": "Aún no hay aperturas. Suelen empezar a llegar a los pocos minutos del envío.",
"No posts found": "No se encontraron entradas",
"No reason given": "Sin motivo",
"No reports yet": "Aún no hay informes",
"No sends yet": "Sin envíos aún",
"No subscribers yet": "Aún no hay suscriptores",
"Nobody here": "No hay nadie aquí",
"Nobody matches «%s».": "Nadie coincide con «%s».",
"Nobody new in the last 30 days.": "Nadie nuevo en los últimos 30 días.",
"Nobody would receive it: the chosen lists have no active subscribers.": "No le llegaría a nadie: las listas elegidas no tienen suscriptores activos.",
"Not configured": "Sin configurar",
"Not confirmed": "Sin confirmar",
"Nothing scheduled.": "Nada programado.",
"Now": "Ahora",
"Now goes out through %s": "Ahora sale por %s",
"Off": "Apagada",
"Off, it is saved but nobody sees it.": "Apagado, se guarda pero nadie lo ve.",
"Off. People come in without confirming.": "Apagada. La gente entra sin confirmar.",
"On": "Encendida",
"On / off": "Encender / apagar",
"On for every form. It avoids fake addresses.": "Encendida para todos los formularios. Evita direcciones falsas.",
"One click and you are in": "Un clic y estás dentro",
"One email a month, no filler": "Un correo al mes, sin relleno",
"Only active subscribers. Whoever is on two lists receives it once. With no list checked, it goes to everyone.": "Solo suscriptores activos. Quien esté en dos listas la recibe una vez. Sin ninguna lista marcada, va a todos.",
"Only blog posts": "Solo las entradas del blog",
"Only from 100 subscribers on (now %s).": "Solo a partir de 100 suscriptores (ahora %s).",
"Only sent campaigns can be resent.": "Solo se pueden reenviar campañas ya enviadas.",
"Only you see it, to tell the forms apart.": "Solo lo ves tú, para distinguir los formularios.",
"Open": "Abrir",
"Opens": "Aperturas",
"Opens per hour": "Aperturas por hora",
"Other": "Otro",
"Others": "Otros",
"Overview": "Resumen",
"Pages": "Páginas",
"Paste it in any page or post. In Elementor, look for the «Dox Orbit» widget.": "Pégalo en cualquier página o entrada. En Elementor, busca el widget «Dox Orbit».",
"Pause": "Pausar",
"Paused": "En pausa",
"Paused «%s»": "En pausa «%s»",
"Person": "Persona",
"Phone": "Móvil",
"Pop-up": "Ventana emergente",
"Port": "Puerto",
"Post": "Entrada",
"Postal address": "Dirección postal",
"Prepare the next one": "Preparar la siguiente",
"Preview text": "Texto previo",
"Put a form on the website": "Pon un formulario en la web",
"Read more": "Leer más",
"Ready to send?": "¿Lista para enviar?",
"Received 3 or more and opened none. Worth cleaning from time to time.": "Recibieron 3 o más y no abrieron ninguno. Conviene limpiarlos de vez en cuando.",
"Recipients": "Destinatarios",
"Recommended: leave at least 50 free per hour.": "Recomendado: dejar al menos 50 libres por hora.",
"Remove": "Quitar",
"Reply to": "Responder a",
"Report": "Informe",
"Reports": "Informes",
"Resend": "Reenviar",
"Resend confirmation": "Reenviar confirmación",
"Rest of the website %s": "Resto de la web %s",
"Resume": "Reanudar",
"Review it": "Revisarla",
"SMTP password": "Contraseña SMTP",
"SMTP server": "Servidor SMTP",
"SMTP user": "Usuario SMTP",
"Save": "Guardar",
"Save form": "Guardar formulario",
"Save the form to get its shortcode.": "Guarda el formulario para tener su shortcode.",
"Saved": "Guardado",
"Saved. Leave it empty to keep it.": "Guardada. Déjala vacía para mantenerla.",
"Saving…": "Guardando…",
"Schedule": "Programar",
"Scheduled": "Programada",
"Scheduled for %s": "Programada para el %s",
"Search": "Buscar",
"Search by email": "Buscar por correo",
"Search by name": "Buscar por nombre",
"Search by subject": "Buscar por asunto",
"Search posts…": "Buscar entradas…",
"See all": "Ver todas",
"See the report": "Ver el informe",
"Send a test": "Enviar una prueba",
"Send me a test": "Enviarme una prueba",
"Send now": "Enviar ahora",
"Send or schedule": "Enviar o programar",
"Send test": "Enviar prueba",
"Send test email": "Enviar correo de prueba",
"Send the welcome email": "Enviar el correo de bienvenida",
"Send yourself a test before it goes out.": "Mándate una prueba antes de que salga.",
"Sender and address": "Remitente y dirección",
"Sender and brand": "Remitente y marca",
"Sending": "Enviando",
"Sending at up to %s per hour.": "Envía hasta %s por hora.",
"Sending speed": "Velocidad de envío",
"Sending «%s»": "Enviando «%s»",
"Sends the confirmation email with these settings, even if they are not saved yet.": "Manda el correo de confirmación con estos ajustes, aunque aún no estén guardados.",
"Sent": "Enviada",
"Server limit:": "Límite del servidor:",
"Set up the form": "Configurar el formulario",
"Settings": "Ajustes",
"Shortcode or Elementor widget": "Shortcode o widget de Elementor",
"Show how many we are": "Enseñar cuántos somos",
"Show it on the website": "Mostrarlo en la web",
"Size": "Tamaño",
"Small": "Pequeño",
"Something went wrong. Reload the page and try again.": "Algo salió mal. Recarga la página e inténtalo otra vez.",
"Something went wrong. Try again.": "Algo salió mal. Inténtalo otra vez.",
"Space": "Espacio",
"Status": "Estado",
"Style": "Estilo",
"Subject": "Asunto",
"Subscribe": "Suscribirme",
"Subscriber": "Suscriptor",
"Subscribers": "Suscriptores",
"Test": "Prueba",
"Test email": "Correo de prueba",
"Test sent to %s": "Prueba enviada a %s",
"Test sent to %s. Check the inbox (and spam).": "Prueba enviada a %s. Revisa la bandeja de entrada (y el spam).",
"Text": "Texto",
"Texts": "Textos",
"Texts, colors and the list are changed in Dox Plugins > Orbit > Forms.": "Los textos, los colores y la lista se cambian en Dox Plugins > Orbit > Formularios.",
"Thanks for confirming. The next email will reach your inbox.": "Gracias por confirmar. El próximo correo te llegará a la bandeja de entrada.",
"Thanks for subscribing. Once a month you will receive what we learn and what we publish, without filler.": "Gracias por suscribirte. Una vez al mes recibirás lo que aprendemos y lo que publicamos, sin relleno.",
"That campaign no longer exists.": "Esa campaña ya no existe.",
"That date is not valid.": "Esa fecha no es válida.",
"That email does not look right.": "Ese correo no parece correcto.",
"That email does not look right. Check it and try again.": "Ese correo no parece correcto. Revísalo e inténtalo otra vez.",
"That subscriber no longer exists.": "Ese suscriptor ya no existe.",
"That time has already passed.": "Esa hora ya pasó.",
"The CAN-SPAM law in the US requires a real postal address in every marketing email: a street address, a PO box or a private mailbox.": "La ley CAN-SPAM de EE. UU. exige una dirección postal real en cada correo de marketing: calle, apartado de correos o buzón privado.",
"The WordPress email": "El correo de WordPress",
"The campaign and its report will be deleted. This cannot be undone.": "Se borrarán la campaña y su informe. No se puede deshacer.",
"The confirmation email": "El correo de confirmación",
"The draft will be deleted. This cannot be undone.": "Se borrará el borrador. No se puede deshacer.",
"The email could not be sent.": "No se pudo enviar el correo.",
"The email could not be sent. Check the sending settings.": "No se pudo enviar el correo. Revisa los ajustes de envío.",
"The email is empty: add a title, a text or an image.": "El correo está vacío: añade un título, un texto o una imagen.",
"The links go through your website for an instant before reaching their destination.": "Los enlaces pasan un instante por tu web antes de llegar a su destino.",
"The number is who joined through each form in 30 days": "El número es quién entró por cada formulario en 30 días",
"The page after confirming": "La página después de confirmar",
"The reply-to email is not valid.": "El correo de respuesta no es válido.",
"The same email": "El mismo correo",
"The same one WooCommerce and the forms use. No cost and no new accounts. For lists of up to a few thousand.": "El mismo que usan WooCommerce y los formularios. Sin coste y sin cuentas nuevas. Para listas de hasta unos pocos miles.",
"The sender email in Settings is not valid.": "El correo del remitente en Ajustes no es válido.",
"The sender email is not valid.": "El correo del remitente no es válido.",
"The whole website": "Toda la web",
"There are unsaved changes.": "Hay cambios sin guardar.",
"There is already a subscriber with that email.": "Ya hay un suscriptor con ese correo.",
"There must be at least one form.": "Tiene que haber al menos un formulario.",
"There must be at least one list.": "Tiene que haber al menos una lista.",
"These fields cannot be filled: %s. The ones that work are {first_name}, {last_name} and {email}.": "Estos campos no se pueden rellenar: %s. Los que funcionan son {first_name}, {last_name} y {email}.",
"These people agreed to receive my emails": "Estas personas aceptaron recibir mis correos",
"They come in as active, without a confirmation email. Whoever is already unsubscribed or bounced is skipped.": "Entran como activos, sin correo de confirmación. Quien ya se dio de baja o rebotó se salta.",
"This address is no longer on our list.": "Esta dirección ya no está en nuestra lista.",
"This address unsubscribed. To come back, use the form on the website.": "Esta dirección se dio de baja. Para volver, usa el formulario de la web.",
"This campaign cannot be deleted while it is sending.": "No se puede borrar una campaña mientras se envía.",
"This campaign cannot be sent from its current state.": "Esta campaña no se puede enviar en el estado en que está.",
"This campaign has already been sent and cannot be edited.": "Esta campaña ya se envió y no se puede editar.",
"This campaign has already gone out and cannot be edited. You can duplicate it to send a new version.": "Esta campaña ya salió y no se puede editar. Puedes duplicarla para enviar una versión nueva.",
"This email is no longer available": "Este correo ya no está disponible",
"This link is no longer valid": "Este enlace ya no es válido",
"This person agreed to receive my emails": "Esta persona aceptó recibir mis correos",
"This person is not waiting for confirmation.": "Esta persona no está pendiente de confirmar.",
"This person unsubscribed. Only they can subscribe again, from a form.": "Esta persona se dio de baja. Solo ella puede volver a suscribirse, desde un formulario.",
"Three steps and you can send your first newsletter. Everything stays in your WordPress.": "Tres pasos y puedes enviar tu primer boletín. Todo se queda en tu WordPress.",
"Title": "Título",
"To the lists": "A las listas",
"To who did not click (%s)": "A quien no hizo clic (%s)",
"To who did not open it (%s)": "A quien no la abrió (%s)",
"To write «Hi, Ana» in the emails.": "Para escribir «Hola, Ana» en los correos.",
"Too many attempts. Try again in a few minutes.": "Demasiados intentos. Inténtalo dentro de unos minutos.",
"Tracking and footer": "Seguimiento y pie",
"Unsaved changes": "Cambios sin guardar",
"Unsubscribe": "Darme de baja",
"Unsubscribed": "Dados de baja",
"Unsubscribes": "Bajas",
"Unsubscribes per send": "Bajas por envío",
"Use this image": "Usar esta imagen",
"View in browser": "Ver en el navegador",
"Visit the blog": "Visitar el blog",
"Waiting for confirmation": "Pendiente de confirmar",
"Welcome email": "Correo de bienvenida",
"Welcome to %s": "Bienvenido a %s",
"Welcome, {first_name|friend}": "Te damos la bienvenida, {first_name|amigo}",
"What is seen next to the subject in the inbox": "Lo que se ve junto al asunto en la bandeja",
"What is this email about?": "¿De qué va este correo?",
"What the image shows, in a few words.": "Lo que muestra la imagen, en pocas palabras.",
"What they see while the confirmation email is on its way.": "Lo que ven mientras les llega el correo de confirmación.",
"What we learn and what we publish. You can unsubscribe with one click.": "Lo que aprendemos y lo que publicamos. Te das de baja con un clic.",
"What you will receive and how often.": "Qué vas a recibir y cada cuánto.",
"When": "Cuándo",
"When a campaign goes out, its opens, clicks and unsubscribes appear here.": "Cuando salga una campaña, aquí aparecerán sus aperturas, clics y bajas.",
"When scrolling down": "Al bajar por la página",
"When scrolling or after a few seconds": "Al bajar o a los pocos segundos",
"Where it appears": "Dónde aparece",
"Where replies arrive, if it is a different address.": "Dónde llegan las respuestas, si es otra dirección.",
"Where they clicked": "Dónde hicieron clic",
"Where they come from": "De dónde llegan",
"Who did not click «%s»": "Quien no hizo clic en «%s»",
"Who did not open «%s»": "Quien no abrió «%s»",
"Who it comes from": "De quién viene",
"Who receives it": "A quién le llega",
"Whoever closes it does not see it again for 14 days, and whoever subscribes does not see it again.": "Quien la cierra no la vuelve a ver en 14 días, y quien se suscribe no la vuelve a ver.",
"Whoever has not received it yet will not get it. This cannot be undone.": "Quien aún no la haya recibido ya no la recibirá. No se puede deshacer.",
"Whoever subscribes receives an email to confirm. It keeps fake and mistyped addresses out, which is what protects your reputation with Gmail. Recommended.": "Quien se suscribe recibe un correo para confirmar. Deja fuera las direcciones falsas o mal escritas, que es lo que protege tu reputación con Gmail. Recomendado.",
"Why some failed": "Por qué fallaron algunos",
"Why they receive it": "Por qué lo reciben",
"With Amazon SES the server quota is not used: the speed only spreads the send.": "Con Amazon SES no se gasta el cupo del servidor: la velocidad solo reparte el envío.",
"With an invisible image. Gmail and the iPhone load it by themselves, so it is a figure on the high side.": "Con una imagen invisible. Gmail y el iPhone la cargan solos, así que es una cifra al alza.",
"With less than 50 free, order emails may have to wait.": "Con menos de 50 libres, los correos de pedidos pueden quedarse esperando.",
"With your name in the fields and «[Test]» in the subject. It does not count in the report.": "Con tu nombre en los campos y «[Prueba]» en el asunto. No cuenta en el informe.",
"WordPress could not send the email.": "WordPress no pudo enviar el correo.",
"WordPress email": "Correo de WordPress",
"Write a subject.": "Escribe un asunto.",
"Write a valid email for the test.": "Escribe un correo válido para la prueba.",
"Write the first campaign": "Escribe la primera campaña",
"Write the first one": "Escribe la primera",
"Write the first one. It saves by itself as you type, and you can send yourself a test before it goes out.": "Escribe la primera. Se guarda sola mientras escribes, y puedes mandarte una prueba antes de que salga.",
"Yes, subscribe me": "Sí, suscribirme",
"You are already unsubscribed": "Ya te habías dado de baja",
"You are receiving this email because you subscribed at %s.": "Recibes este correo porque te suscribiste en %s.",
"You are subscribed": "Ya estás suscrito",
"You are unsubscribed": "Estás dado de baja",
"You have not sent yourself a test yet.": "Aún no te has mandado una prueba.",
"You were already subscribed. Thanks!": "Ya estabas suscrito. ¡Gracias!",
"Your list starts here": "Tu lista empieza aquí",
"Your name": "Tu nombre",
"Your readers open most around %s.": "Tus lectores abren sobre todo hacia las %s.",
"Your server lets out <b>%s emails per hour</b> per website. Whatever the newsletter does not use stays free for orders, passwords and forms.": "Tu servidor deja salir <b>%s correos por hora</b> por web. Lo que no use el boletín queda libre para pedidos, contraseñas y formularios.",
"Your session expired. Reload the page.": "Tu sesión caducó. Recarga la página.",
"clicked": "hizo clic",
"delivered": "entregados",
"finishes %1$s around %2$s": "termina el %1$s hacia las %2$s",
"finishes today around %s": "termina hoy hacia las %s",
"hour": "hora",
"just now": "ahora mismo",
"opened": "abrió",
"opened it": "la abrió",
"seconds": "segundos",
"sent": "enviados",
"unsubscribed": "se dieron de baja",
"you@email.com": "tu@correo.com",
}
PL = {
"%s waiting to confirm": ["%s pendiente de confirmar", "%s pendientes de confirmar"],
"Last campaign · Gmail and iPhone open some by themselves": ["Última campaña · Gmail y el iPhone abren algunas solos", "Últimas %d campañas · Gmail y el iPhone abren algunas solos"],
"%s person in the last one": ["%s persona en la última", "%s personas en la última"],
"%s person": ["%s persona", "%s personas"],
"%s active subscriber": ["%s suscriptor activo", "%s suscriptores activos"],
"%s failed": ["%s falló", "%s fallaron"],
}
